package com.example.studentmanagement.mapper;

import com.example.studentmanagement.dto.StudentAdminRequest;
import com.example.studentmanagement.dto.StudentDto;
import com.example.studentmanagement.dto.StudentRegistrationRequest;
import com.example.studentmanagement.model.Student;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.mapstruct.MappingTarget;
import org.mapstruct.ReportingPolicy;

import java.util.List;

/**
 * MapStruct mapper between {@link Student} and the DTOs.
 *
 * <p>Conversion notes:
 * <ul>
 *   <li>entity {@code Course} &rarr; dto {@code String} uses {@link Enum#name()} (MapStruct default).</li>
 *   <li>request {@code String} &rarr; entity {@code Course} uses {@code Course.valueOf(...)} (MapStruct default).</li>
 *   <li>{@code courseDisplayName} is derived from the enum's display name via an expression.</li>
 * </ul>
 */
@Mapper(componentModel = "spring", unmappedTargetPolicy = ReportingPolicy.IGNORE)
public interface StudentMapper {

    @Mapping(target = "courseDisplayName",
            expression = "java(entity.getCourse() != null ? entity.getCourse().getDisplayName() : null)")
    StudentDto toDto(Student entity);

    List<StudentDto> toDtoList(List<Student> entities);

    /** studentNumber, enrollmentYear and gpa are set by the service, not the public form. */
    @Mapping(target = "id", ignore = true)
    @Mapping(target = "studentNumber", ignore = true)
    @Mapping(target = "enrollmentYear", ignore = true)
    @Mapping(target = "gpa", ignore = true)
    Student toEntity(StudentRegistrationRequest request);

    /** studentNumber is generated by the service; id is DB-assigned. */
    @Mapping(target = "id", ignore = true)
    @Mapping(target = "studentNumber", ignore = true)
    Student toEntity(StudentAdminRequest request);

    /** Updates an existing entity in place; never touches id or studentNumber. */
    @Mapping(target = "id", ignore = true)
    @Mapping(target = "studentNumber", ignore = true)
    void updateEntityFromAdminRequest(StudentAdminRequest request, @MappingTarget Student entity);
}
