apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: student-management-data
  labels:
    app: student-management
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
